- name: Copy elastic repo file
  ansible.builtin.template:
    src: elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: Install filebeat
  ansible.builtin.yum:
    name: filebeat
    state: installed

- name: Copy filebeat
  ansible.builtin.template:
    src: filebeat-org.yml
    dest: /etc/filebeat/filebeat-org.yml

- name: start filebeat
  ansible.builtin.systemd:
    name: filebeat
    state: restarted
    enabled: yes

- name: Copy logstash config
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: Restart logstash
  ansible.builtin.systemd:
    name: logstash
    state: restarted
    enabled: yes